import { Component, OnInit } from '@angular/core';
import { DatePipe, NgFor, NgIf } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../core/api.service';
import { AuthService } from '../../core/auth.service';
import { RecordItem, User } from '../../models';

@Component({ selector: 'vf-dashboard', standalone: true, imports: [NgFor, NgIf, DatePipe, FormsModule], template: `
<div class="page-shell"><header class="topbar"><div class="breadcrumbs">Workspace <span>/</span> <b>Overview</b></div><div class="top-actions"><span class="live-status"><i></i> All systems operational</span><button class="icon-button" title="Notifications">♧<i></i></button><span class="top-avatar">{{ initials(user?.name || '') }}</span></div></header>
<section class="page-content"><div class="welcome-row"><div><div class="eyebrow"><span></span> TUESDAY, OCTOBER 06, 2026</div><h1>{{ greeting }}, {{ firstName }}<span class="heading-period">.</span></h1><p class="page-subtitle">Here’s what’s happening across your verification workspace.</p></div><div class="delay-control"><span class="delay-icon">◷</span><label for="delay-select">API response</label><select id="delay-select" [ngModel]="auth.delayMs()" (ngModelChange)="changeDelay($event)"><option [ngValue]="0">Instant</option><option [ngValue]="700">700 ms</option><option [ngValue]="1800">1.8 sec</option><option [ngValue]="3000">3 sec</option></select><span class="delay-caption">Async demo</span></div></div>
<div class="welcome-banner"><div class="banner-copy"><span class="banner-label">YOUR VERIFICATION DESK</span><h2>Good work deserves<br>a trusted record.</h2><p>One clear view of the people, histories, and milestones that move your team forward.</p><div class="banner-proof"><span>✓</span> Transparent by design <i></i> Private by default</div></div><div class="banner-visual"><div class="banner-ring ring-a"></div><div class="banner-ring ring-b"></div><div class="banner-doc"><div class="doc-top"><span class="doc-logo">v</span><span class="doc-stamp">VERIFIED</span></div><div class="doc-line long"></div><div class="doc-line mid"></div><div class="doc-line short"></div><div class="doc-sign">{{ initials(user?.name || '') }}<span>✓</span></div></div><div class="floating-check">✓</div><div class="floating-label">VERIFIABLE <b>BY DESIGN</b></div></div></div>
<div class="section-heading"><div><div class="eyebrow"><span></span> YOUR ACTIVITY</div><h2>Verification records</h2></div><div class="record-summary"><span class="summary-dot"></span> {{ records.length }} records <span class="summary-sep">·</span> Updated just now</div></div>
<div class="stats-grid"><article class="stat-card"><div class="stat-top"><span class="stat-icon icon-green">✓</span><span class="stat-trend">↗ 12%</span></div><div class="stat-number">{{ verifiedCount }}</div><div class="stat-caption">Verified records</div><div class="stat-foot">A solid foundation of trust</div></article><article class="stat-card"><div class="stat-top"><span class="stat-icon icon-amber">◷</span><span class="stat-neutral">IN REVIEW</span></div><div class="stat-number">{{ reviewCount }}</div><div class="stat-caption">In progress</div><div class="stat-foot">Moving through the process</div></article><article class="stat-card"><div class="stat-top"><span class="stat-icon icon-lilac">⌁</span><span class="stat-neutral">THIS MONTH</span></div><div class="stat-number">{{ records.length }}</div><div class="stat-caption">Total records</div><div class="stat-foot">Across your workspace access</div></article><article class="stat-card security-card"><div class="security-icon">◇</div><div><div class="security-title">Privacy first</div><div class="security-description">Your records stay protected with role-based access.</div><span class="security-link">ACCESS IS ALWAYS RESPECTED <b>↗</b></span></div></article></div>
<div class="records-card"><div class="records-toolbar"><div><h3>Recent records</h3><p>Employment histories shared with your workspace</p></div><button class="text-action" (click)="refresh()">↻ <span>Refresh</span></button></div><div class="loading-row" *ngIf="loading"><span class="spinner"></span> Loading records securely…</div><div class="error-note" *ngIf="!loading && error">{{ error }} <button class="inline-retry" (click)="refresh()">Try again</button></div><div class="table-scroll" *ngIf="!loading && !error"><table><thead><tr><th>PERSON</th><th>EMPLOYER</th><th>RECORD TYPE</th><th>STATUS</th><th>LAST UPDATED</th><th></th></tr></thead><tbody><tr *ngFor="let record of records"><td><div class="person-cell"><span class="person-avatar" [class]="'person-avatar hue-' + avatarHue(record.person)">{{ initials(record.person) }}</span><span><b>{{ record.person }}</b><small>{{ record.role }}</small></span></div></td><td><span class="company-name">{{ record.company }}</span></td><td><span class="type-pill">{{ record.type }}</span></td><td><span class="status-pill" [class.status-verified]="record.status === 'Verified'" [class.status-progress]="record.status === 'In progress'" [class.status-review]="record.status === 'Needs review'"><i></i>{{ record.status }}</span></td><td class="date-cell">{{ record.updatedAt | date:'MMM d, y' }}</td><td><button class="row-more" title="Record reference" [attr.aria-label]="'Reference ' + record.reference">···</button></td></tr><tr *ngIf="records.length === 0"><td colspan="6" class="empty-state">No records are available for this account.</td></tr></tbody></table></div><div class="records-foot"><span>Showing <b>{{ records.length }}</b> {{ records.length === 1 ? 'record' : 'records' }} available to you</span><span class="records-privacy">◇ YOUR VIEW IS ROLE-BASED AND PRIVATE</span></div></div>
<footer class="page-footer"><span>VERIFLOW <i>·</i> TRUST, VERIFIED.</span><span>Built with care for the people behind the work.</span></footer></section></div>` })
export class DashboardComponent implements OnInit {
  user: User | null = null; records: RecordItem[] = []; loading = true; error = '';
  constructor(private api: ApiService, readonly auth: AuthService) {}
  ngOnInit(): void { this.load(); this.api.me().subscribe({ next: user => { this.user = user; this.auth.currentUser.set(user); localStorage.setItem('veriflow.user', JSON.stringify(user)); }, error: () => {} }); }
  load(): void { this.loading = true; this.error = ''; this.api.records().subscribe({ next: rows => { this.records = rows; this.loading = false; }, error: () => { this.records = []; this.error = 'We could not load records right now.'; this.loading = false; } }); }
  refresh(): void { this.load(); }
  changeDelay(value: number): void { this.auth.setDelay(Number(value)); this.load(); }
  get firstName(): string { return (this.user?.name ?? this.auth.currentUser()?.name ?? 'there').split(' ')[0]; }
  get greeting(): string { const hour = new Date().getHours(); return hour < 12 ? 'Good morning' : hour < 18 ? 'Good afternoon' : 'Good evening'; }
  get verifiedCount(): number { return this.records.filter(row => row.status === 'Verified').length; }
  get reviewCount(): number { return this.records.filter(row => row.status !== 'Verified').length; }
  initials(name: string): string { return name.split(' ').map(part => part[0] ?? '').slice(0, 2).join('').toUpperCase() || 'VF'; }
  avatarHue(name: string): number { return [...name].reduce((sum, char) => sum + char.charCodeAt(0), 0) % 5; }
}
