import { Component, OnInit } from '@angular/core';
import { NgFor, NgIf } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../core/api.service';
import { User, UserRole } from '../../models';

@Component({ selector: 'vf-users', standalone: true, imports: [NgFor, NgIf, FormsModule], template: `
<div class="page-shell"><header class="topbar"><div class="breadcrumbs">Workspace <span>/</span> <b>People</b></div><div class="top-actions"><span class="live-status"><i></i> All systems operational</span><span class="top-avatar">MF</span></div></header><section class="page-content admin-content"><div class="welcome-row"><div><div class="eyebrow"><span></span> WORKSPACE DIRECTORY</div><h1>People<span class="heading-period">.</span></h1><p class="page-subtitle">Manage the people who make trust possible.</p></div><button class="button button-primary add-user" (click)="openCreate()"><span>＋</span> Add a person</button></div>
<div class="admin-banner"><div><span class="banner-label">ACCESS, WITH INTENTION</span><h2>Right people. Right access.</h2><p>Every account has a role, so sensitive records reach the people who need them.</p></div><div class="admin-metric"><span>ACTIVE PEOPLE</span><b>{{ activeCount }}<small> / {{ users.length }}</small></b><i>Across your workspace</i></div><div class="admin-shield">◇</div></div>
<div class="section-heading admin-section-heading"><div><div class="eyebrow"><span></span> TEAM ACCESS</div><h2>Workspace people</h2></div><div class="record-summary"><span class="summary-dot"></span> {{ users.length }} accounts</div></div>
<div class="records-card people-card"><div class="records-toolbar"><div><h3>Directory</h3><p>People with access to this verification workspace</p></div><div class="directory-search"><span>⌕</span><input [(ngModel)]="search" placeholder="Find a person…" aria-label="Search people"></div></div><div class="loading-row" *ngIf="loading"><span class="spinner"></span> Loading workspace people…</div><div class="table-scroll" *ngIf="!loading"><table><thead><tr><th>PERSON</th><th>ROLE</th><th>DEPARTMENT</th><th>STATUS</th><th>JOINED</th><th></th></tr></thead><tbody><tr *ngFor="let person of filteredUsers"><td><div class="person-cell"><span class="person-avatar" [class]="'person-avatar hue-' + hue(person.name)">{{ initials(person.name) }}</span><span><b>{{ person.name }}</b><small>{{ person.email }}</small></span></div></td><td><span class="role-label"><i [class.admin-role-dot]="person.role === 'admin'"></i>{{ person.role === 'admin' ? 'Administrator' : 'General user' }}</span></td><td class="date-cell">{{ person.department }}</td><td><span class="status-pill" [class.status-verified]="person.status === 'active'" [class.status-review]="person.status === 'inactive'"><i></i>{{ person.status === 'active' ? 'Active' : 'Inactive' }}</span></td><td class="date-cell">{{ person.joinedAt }}</td><td><div class="row-actions"><button title="Edit person" (click)="openEdit(person)">Edit</button><button title="Remove person" (click)="remove(person)" [disabled]="person.id === myId">···</button></div></td></tr><tr *ngIf="filteredUsers.length === 0"><td colspan="6" class="empty-state">No people match that search.</td></tr></tbody></table></div><div class="records-foot"><span>Showing <b>{{ filteredUsers.length }}</b> of <b>{{ users.length }}</b> accounts</span><span class="records-privacy">◇ ADMINISTRATOR ACCESS</span></div></div><footer class="page-footer"><span>VERIFLOW <i>·</i> TRUST, VERIFIED.</span><span>Thoughtful access builds lasting trust.</span></footer>
<div class="modal-backdrop" *ngIf="editing" (click)="close()"><section class="user-modal" (click)="$event.stopPropagation()"><button class="modal-close" (click)="close()">×</button><div class="eyebrow"><span></span> {{ draft.id ? 'ACCOUNT DETAILS' : 'NEW ACCOUNT' }}</div><h2>{{ draft.id ? 'Edit person' : 'Add a person' }}</h2><p class="login-lead">Give this person the right place in your workspace.</p><form (ngSubmit)="save()"><label for="name">Full name</label><input id="name" name="name" class="form-input" [(ngModel)]="draft.name" required><label for="email">Work email</label><input id="email" name="email" type="email" class="form-input" [(ngModel)]="draft.email" required><div class="form-two"><div><label for="department">Department</label><input id="department" name="department" class="form-input" [(ngModel)]="draft.department" required></div><div><label for="role-edit">Role</label><select id="role-edit" name="role" class="form-input" [(ngModel)]="draft.role"><option value="user">General user</option><option value="admin">Administrator</option></select></div></div><div *ngIf="!draft.id"><label for="new-password">Temporary password</label><input id="new-password" name="password" type="password" class="form-input" [(ngModel)]="draft.password" required minlength="6"></div><div class="modal-error" *ngIf="error">{{ error }}</div><div class="modal-buttons"><button type="button" class="button button-quiet" (click)="close()">Cancel</button><button class="button button-primary" [disabled]="saving">{{ saving ? 'Saving…' : draft.id ? 'Save changes' : 'Create account' }}</button></div></form></section></div></section></div>` })
export class UsersComponent implements OnInit {
  users: User[] = []; loading = true; saving = false; editing = false; search = ''; error = ''; myId = '';
  draft: Partial<User> & { password?: string } = {};
  constructor(private api: ApiService) { try { this.myId = JSON.parse(localStorage.getItem('veriflow.user') ?? '{}').id ?? ''; } catch {} }
  ngOnInit(): void { this.load(); }
  load(): void { this.loading = true; this.api.users().subscribe({ next: users => { this.users = users; this.loading = false; }, error: () => { this.error = 'Could not load the workspace directory.'; this.loading = false; } }); }
  get filteredUsers(): User[] { const term = this.search.toLowerCase().trim(); return this.users.filter(user => `${user.name} ${user.email} ${user.department}`.toLowerCase().includes(term)); }
  get activeCount(): number { return this.users.filter(user => user.status === 'active').length; }
  openCreate(): void { this.draft = { name: '', email: '', role: 'user' as UserRole, department: '', password: '', status: 'active' }; this.error = ''; this.editing = true; }
  openEdit(user: User): void { this.draft = { ...user }; this.error = ''; this.editing = true; }
  close(): void { this.editing = false; }
  save(): void { this.saving = true; this.error = ''; this.api.saveUser(this.draft).subscribe({ next: () => { this.saving = false; this.editing = false; this.load(); }, error: (e: { error?: { message?: string } }) => { this.saving = false; this.error = e.error?.message ?? 'Could not save this account.'; } }); }
  remove(user: User): void { if (!confirm(`Remove ${user.name} from the workspace?`)) return; this.api.deleteUser(user.id).subscribe({ next: () => this.load(), error: () => this.error = 'Could not remove this account.' }); }
  initials(name: string): string { return name.split(' ').map(part => part[0] ?? '').slice(0, 2).join('').toUpperCase(); }
  hue(name: string): number { return [...name].reduce((sum, char) => sum + char.charCodeAt(0), 0) % 5; }
}
